https://www.acmicpc.net/problem/12891

## 문제
평소에 문자열을 가지고 노는 것을 좋아하는 민호는 DNA 문자열을 알게 되었다. DNA 문자열은 모든 문자열에 등장하는 문자가 {‘A’, ‘C’, ‘G’, ‘T’} 인 문자열을 말한다. 예를 들어 “ACKA”는 DNA 문자열이 아니지만 “ACCA”는 DNA 문자열이다. 이런 신비한 문자열에 완전히 매료된 민호는 임의의 DNA 문자열을 만들고 만들어진 DNA 문자열의 부분문자열을 비밀번호로 사용하기로 마음먹었다.

하지만 민호는 이러한 방법에는 큰 문제가 있다는 것을 발견했다. 임의의 DNA 문자열의 부분문자열을 뽑았을 때 “AAAA”와 같이 보안에 취약한 비밀번호가 만들어 질 수 있기 때문이다. 그래서 민호는 부분문자열에서 등장하는 문자의 개수가 특정 개수 이상이여야 비밀번호로 사용할 수 있다는 규칙을 만들었다.

임의의 DNA문자열이 “AAACCTGCCAA” 이고 민호가 뽑을 부분문자열의 길이를 4라고 하자. 그리고 부분문자열에 ‘A’ 는 1개 이상, ‘C’는 1개 이상, ‘G’는 1개 이상, ‘T’는 0개 이상이 등장해야 비밀번호로 사용할 수 있다고 하자. 이때 “ACCT” 는 ‘G’ 가 1 개 이상 등장해야 한다는 조건을 만족하지 못해 비밀번호로 사용하지 못한다. 하지만 “GCCA” 은 모든 조건을 만족하기 때문에 비밀번호로 사용할 수 있다.

민호가 만든 임의의 DNA 문자열과 비밀번호로 사용할 부분분자열의 길이, 그리고 {‘A’, ‘C’, ‘G’, ‘T’} 가 각각 몇번 이상 등장해야 비밀번호로 사용할 수 있는지 순서대로 주어졌을 때 민호가 만들 수 있는 비밀번호의 종류의 수를 구하는 프로그램을 작성하자. 단 부분문자열이 등장하는 위치가 다르다면 부분문자열이 같다고 하더라도 다른 문자열로 ## 취급한다.

입력
첫 번째 줄에 민호가 임의로 만든 DNA 문자열 길이 |S|와 비밀번호로 사용할 부분문자열의 길이 |P| 가 주어진다. (1 ≤ |P| ≤ |S| ≤ 1,000,000)

두번 째 줄에는 민호가 임의로 만든 DNA 문자열이 주어진다.

세번 째 줄에는 부분문자열에 포함되어야 할 {‘A’, ‘C’, ‘G’, ‘T’} 의 최소 개수가 공백을 구분으로 주어진다. 각각의 수는 |S| 보다 작거나 같은 음이 아닌 정수이며 총 합은 |S| 보다 작## 거나 같음이 보장된다.

출력
첫 번째 줄에 민호가 만들 수 있는 비밀번호의 종류의 수를 출력해라.

In [10]:
s, p = map(int, input().split())
dna = input()
num_a, num_c, num_g, num_t = map(int, input().split())

 4 2
 GATA
 1 0 0 1


In [20]:
left_index = 0
right_index = p
count = 0

In [21]:
while right_index <= s:
    check_dna = dna[left_index:right_index]
    
    # 체크할 문자열에서 각 알파벳 숫자 체크
    check_a, check_c, check_g, check_t = 0, 0, 0, 0
    for char in check_dna:
        if char == 'A':
            check_a += 1
        elif char == 'C':
            check_c += 1
        elif char == 'G':
            check_g += 1
        else:
            check_t += 1

    # 만약 알파벳 숫자가 조건을 만족하면 카운트 증가
    if check_a >= num_a and check_c >= num_c and check_g >= num_g and check_t >= num_t:
        count += 1
    left_index += 1
    right_index += 1

1 0 1 0
1 0 0 1
1 0 0 1


시간 초과.  
아무래도 각 구간 내에 알파벳 숫자를 바로 확인할 수 있는 리스트를 미리 생성해두는 것이 정답인 것 같다.

In [23]:
[1, 0, 0, 0] + [0, 1, 0, 0]

[1, 0, 0, 0, 0, 1, 0, 0]

In [27]:
import numpy as np

a = np.array([1, 0, 0, 0])
b = np.array([0, 1, 0, 0])

In [29]:
a+b

array([1, 1, 0, 0])

In [30]:
a[0]

1

In [37]:
dna_converted = [0]*s

for i in range(s):
    if dna[i] == 'A':
        dna_converted[i] = np.array([1, 0, 0, 0])
    elif dna[i] == 'C':
        dna_converted[i] = np.array([0, 1, 0, 0])
    elif dna[i] == 'G':
        dna_converted[i] = np.array([0, 0, 1, 0])
    else:
        dna_converted[i] = np.array([0, 0, 0, 1])

In [38]:
dna_converted

[array([0, 0, 1, 0]),
 array([1, 0, 0, 0]),
 array([0, 0, 0, 1]),
 array([1, 0, 0, 0])]

In [39]:
check_dna = dna_converted[0:2]

In [43]:
sum(dna_converted[0:3])

array([1, 0, 1, 1])

In [44]:
left_index = 0
right_index = p
count = 0
condition = np.array([num_a, num_c, num_g, num_t])

In [46]:
while right_index <= s:
    check_dna = sum(dna_converted[left_index:right_index])
    
    # 만약 알파벳 숫자가 조건을 만족하면 카운트 증가
    if check_dna[0] >= condition[0] and check_dna[1] >= condition[1] and check_dna[2] >= condition[2] and check_dna[3] >= condition[3]:
        count += 1
        
    left_index += 1
    right_index += 1

In [48]:
count

2

In [49]:
import numpy as np

s, p = map(int, input().split())
dna = input()
num_a, num_c, num_g, num_t = map(int, input().split())

left_index = 0
right_index = p
count = 0
condition = np.array([num_a, num_c, num_g, num_t])

dna_converted = [0]*s

# 각 알파벳 분포 정보를 담고 있는 넘파이 배열 생성
for i in range(s):
    if dna[i] == 'A':
        dna_converted[i] = np.array([1, 0, 0, 0])
    elif dna[i] == 'C':
        dna_converted[i] = np.array([0, 1, 0, 0])
    elif dna[i] == 'G':
        dna_converted[i] = np.array([0, 0, 1, 0])
    else:
        dna_converted[i] = np.array([0, 0, 0, 1])

while right_index <= s:
    check_dna = sum(dna_converted[left_index:right_index])
    
    # 만약 알파벳 숫자가 조건을 만족하면 카운트 증가
    if check_dna[0] >= condition[0] and check_dna[1] >= condition[1] and check_dna[2] >= condition[2] and check_dna[3] >= condition[3]:
        count += 1
        
    left_index += 1
    right_index += 1
    
print(count)

 4 2
 GATA
 1 0 0 1


2


문제가 생겼다. 백준 사이트에서 numpy library를 제공하지 않는다...

In [ ]:
left_index = 0
right_index = p
count = 0

In [51]:
while right_index <= s:
    check_dna = dna[left_index:right_index]
    
  # 만약 알파벳 숫자가 조건을 만족하면 카운트 증가
    if check_dna.count('A') >= num_a :
        if check_dna.count('C') >= num_c :
            if check_dna.count('G') >= num_g :
                if check_dna.count('T') >= num_t :
                    count ++ 1
            else: pass
        else: pass
    else: pass

    left_index += 1
    right_index += 1

In [52]:
count

2

역시 시간 초과... 부분합처럼 특정 구간 설정 시 해당 카운트를 알 수 있도록 조정해보자.

In [53]:
dna

'GATA'

In [64]:
dna_converted = [0]*s

for i in range(s):
    if dna[i] == 'A':
        dna_converted[i] = 2
    elif dna[i] == 'C':
        dna_converted[i] = 3
    elif dna[i] == 'G':
        dna_converted[i] = 5
    else:
        dna_converted[i] = 7

condition = (2**num_a)*(3**num_c)*(5**num_g)*(7**num_t)

In [65]:
dna_converted

[5, 2, 7, 2]

In [66]:
condition

14

In [67]:
import math

while right_index <= s:
    check_num = math.prod(dna[left_index:right_index])
    
    if check_num % condition == 0:
        count += 1
        
    left_index += 1
    right_index += 1

In [68]:
count

2

In [71]:
import math

s, p = map(int, input().split())
dna = input()
num_a, num_c, num_g, num_t = map(int, input().split())

left_index = 0
right_index = p
count = 0

dna_converted = [0]*s

# 문자열을 소수로 변환
for i in range(s):
    if dna[i] == 'A':
        dna_converted[i] = 2
    elif dna[i] == 'C':
        dna_converted[i] = 3
    elif dna[i] == 'G':
        dna_converted[i] = 5
    else:
        dna_converted[i] = 7

# 조건식은 소수의 곱이므로, 조건 충족 시 나눈 몫이 0이 된다.
condition = (2**num_a)*(3**num_c)*(5**num_g)*(7**num_t)

# 비교적 간단해진 루프문
while right_index <= s:
    check_num = math.prod(dna_converted[left_index:right_index])
    
    if check_num % condition == 0:
        count += 1
        
    left_index += 1
    right_index += 1

print(count)

 4 2
 GATA
 1 0 0 1


결과는 시간 초과..  
다시 처음 접근 방식으로 돌아가서, 구간이 설정되었을 때마다 모든 문자열을 다 탐색하는 게 아니라, 왼쪽 문자열을 빼고 오른쪽 문자열을 추가하는 식으로 접근하면 연산 부하를 많이 줄일 수 있다.

In [ ]:
left_index = 0
right_index = p
count = 0

In [76]:
def check(left_index, right_index, dna, check_list):

    # 초기 호출 시 작업
    if not check_list :
        check_a, check_c, check_g, check_t = 0, 0, 0, 0
        for char in dna[left_index:right_index]:
            if char == 'A':
                check_a += 1
            elif char == 'C':
                check_c += 1
            elif char == 'G':
                check_g += 1
            else:
                check_t += 1
        return [check_a, check_c, check_g, check_t]

    # 재호출 시 작업 : 가장 왼쪽 숫자를 버리고, 가장 오른쪽 숫자를 추가
    else :
        if dna[left_index-1] == 'A':
            check_list[0] -= 1
        elif dna[left_index-1] == 'C':
            check_list[1] -= 1
        elif dna[left_index-1] == 'G':
            check_list[2] -= 1
        else:
            check_list[3] -= 1  

        if dna[right_index-1] == 'A':
            check_list[0] -= 1
        elif dna[right_index-1] == 'C':
            check_list[1] -= 1
        elif dna[right_index-1] == 'G':
            check_list[2] -= 1
        else:
            check_list[3] -= 1  

        return checklist

In [78]:
def count_plus(check_list, condition, count):
    if check_list[0] >= condition[0]:
        if check_list[1] >= condition[1]:
            if check_list[2] >= condition[2]:
                if check_list[3] >= condition[3]:
                    count += 1
                    return count
                else : return count
            else : return count
        else : return count
    else : return count

In [77]:
condition = [num_a, num_c, num_g, num_t]

In [79]:
check_list = []    

while right_index <= s:
    # 체크할 문자열에서 각 알파벳 숫자 체크
    check_list = check(left_index, right_index, dna, check_list)

    # 만약 알파벳 숫자가 조건을 만족하면 카운트 증가
    count = count_plus(check_list, condition, count)
    left_index += 1
    right_index += 1

In [80]:
count

2

In [84]:
def check(left_index, right_index, dna, check_list):

    # 초기 호출 시 작업
    if not check_list :
        check_a, check_c, check_g, check_t = 0, 0, 0, 0
        for char in dna[left_index:right_index]:
            if char == 'A':
                check_a += 1
            elif char == 'C':
                check_c += 1
            elif char == 'G':
                check_g += 1
            else:
                check_t += 1
        return [check_a, check_c, check_g, check_t]

    # 재호출 시 작업 : 가장 왼쪽 숫자를 버리고, 가장 오른쪽 숫자를 추가
    else :
        if dna[left_index-1] == 'A':
            check_list[0] -= 1
        elif dna[left_index-1] == 'C':
            check_list[1] -= 1
        elif dna[left_index-1] == 'G':
            check_list[2] -= 1
        else:
            check_list[3] -= 1  

        if dna[right_index-1] == 'A':
            check_list[0] += 1
        elif dna[right_index-1] == 'C':
            check_list[1] += 1
        elif dna[right_index-1] == 'G':
            check_list[2] += 1
        else:
            check_list[3] += 1  

        return check_list
        
def count_plus(check_list, condition, count):
    if check_list[0] >= condition[0]:
        if check_list[1] >= condition[1]:
            if check_list[2] >= condition[2]:
                if check_list[3] >= condition[3]:
                    count += 1
                    return count
                else : return count
            else : return count
        else : return count
    else : return count
    
s, p = map(int, input().split())
dna = input()
condition = list(map(int, input().split()))
check_list = []

left_index = 0
right_index = p
count = 0        
        
while right_index <= s:
    # 체크할 문자열에서 각 알파벳 숫자 체크
    check_list = check(left_index, right_index, dna, check_list)
    # print(check_list, condition)

    # 만약 알파벳 숫자가 조건을 만족하면 카운트 증가
    count = count_plus(check_list, condition, count)
    left_index += 1
    right_index += 1
     
print(count)        

 4 2
 GATA
 1 0 0 1


[1, 0, 1, 0] [1, 0, 0, 1]
[1, 0, 0, 1] [1, 0, 0, 1]
[1, 0, 0, 1] [1, 0, 0, 1]
2


성공!